name: CI

on:
  push:
    branches:
      - '**'
        
env:
    APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    APPLITOOLS_BATCH_ID: ${{ github.sha }}
    EYES_SERVER: ${{eyesapi.applitools.com}}
    GITHUB_SERVER: ${{github.com}}
    URL: ${{https://${{eyesapi.applitools.com}}/api/externals/github/servers/${{github.com}}/commit/${{ github.sha }}/complete?apiKey=${{ secrets.APPLITOOLS_API_KEY }}
    HEADER: "Content-Type: application/json --data `{\"serverId\": ${{github.com}}, \"commitSha\": ${{ github.sha }}}`"
    EXTRA_INFO: "-H $header  -v -L"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log Git SHA
        run: echo "$GITHUB_SHA"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - name: Run Tests
        run: npm run cypress:ci
    
  batch-completion-notification:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status 
        uses: wei/curl@v1.1.1
        with:
          args: curl -X POST $url $extraInfo
